name: Databricks CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # 1. Remove old CLI v1
      - name: Remove old Databricks CLI
        run: |
          sudo rm -f /usr/local/bin/databricks || true
          pip uninstall -y databricks-cli || true

      # 2. Install Databricks CLI v2
      - name: Install Databricks CLI v2
        run: |
          curl -L -o databricks.tar.gz https://github.com/databricks/cli/releases/latest/download/databricks_linux_amd64.tar.gz
          tar -xzf databricks.tar.gz
          chmod +x databricks
          sudo mv databricks /usr/local/bin/databricks
          databricks version

      - name: Check CLI Version
        run: databricks version

      - name: Configure Databricks Auth
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: echo "Auth loaded."

      - name: Validate Databricks Bundle
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: databricks bundle validate

      - name: Deploy Bundle
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: databricks bundle deploy --target dev

      - name: Run Databricks Job
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: databricks bundle run --job poc_ingest_job --target dev
