Run databricks bundle validate
  databricks bundle validate
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.10.19/x64
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.10.19/x64/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.10.19/x64
    Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.10.19/x64
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.10.19/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.10.19/x64/lib
    DATABRICKS_HOST: ***
    DATABRICKS_TOKEN: ***
Usage: databricks [OPTIONS] COMMAND [ARGS]...
Try 'databricks -h' for help.

Error: No such command 'bundle'.

Warning: The version of the CLI you are using is deprecated.
To migrate to the new CLI, see https://docs.databricks.com/dev-tools/cli/migrate.html.

In the new CLI, commands and flags might be different.
The preceding migration guide provides guidance about how to adapt your commands accordingly.
